export const indexParent = [
  {
    budget_cost_unit: '',
    budget_cost_value: '0',
    budget_fact_unit: '',
    budget_fact_value: '0',
    budget_plan_unit: '',
    budget_plan_value: '0',
    denotation: 'РСТ-2024',
    description: 'Описание проекта 1',
    filesfolder_name: null,
    goal: 'Цель проекта 1',
    guid: '3386feff-1b42-44a7-8345-6289eac1b20',
    id: '33',
    mainscheduledplan_actualdurationindays: '0',
    mainscheduledplan_actualenddate: null,
    mainscheduledplan_actualstartdate: '2024-01-20T09:00:00',
    mainscheduledplan_durationindays: '394',
    mainscheduledplan_enddate: '31.01.2027',
    mainscheduledplan_name: 'План проекта 1',
    mainscheduledplan_progress: '25 %',
    mainscheduledplan_projectelemanswerableuser_photo: null,
    mainscheduledplan_projectelemanswerableuser_shortname: 'Петров П.П.',
    mainscheduledplan_s_guid: '33d7059a-f54a-47e6-ab8b-1b4d8d995a60',
    mainscheduledplan_startdate: '01.08.2025',
    name: 'Проект 1: Разработка системы',
    number: 1,
    parent: null,
    result: 'В процессе',
    s_classid: 'Портфель',
    type: 'Портфель',
  },
  {
    budget_cost_unit: 'руб',
    budget_cost_value: '1679952',
    budget_fact_unit: 'руб',
    budget_fact_value: '1902148',
    budget_plan_unit: 'руб',
    budget_plan_value: '1523073',
    denotation: 'РНП-2024',
    description: 'Описание проекта 2',
    filesfolder_name: 'project_files',
    goal: 'Цель проекта 2',
    guid: '3486feff-1b42-44a7-8345-6289eac1b21',
    id: '34',
    mainscheduledplan_actualdurationindays: '0',
    mainscheduledplan_actualenddate: null,
    mainscheduledplan_actualstartdate: null,
    mainscheduledplan_durationindays: '343',
    mainscheduledplan_enddate: '31.01.2027',
    mainscheduledplan_name: 'План проекта 2',
    mainscheduledplan_progress: '75 %',
    mainscheduledplan_projectelemanswerableuser_photo: null,
    mainscheduledplan_projectelemanswerableuser_shortname: 'Иванов И.И.',
    mainscheduledplan_s_guid: '34d7059a-f54a-47e6-ab8b-1b4d8d995a61',
    mainscheduledplan_startdate: '01.08.2025',
    name: 'Проект 2: Модернизация технологии',
    number: 2,
    parent: '33',
    result: 'В процессе',
    s_classid: 'Проект',
    type: 'Проект',
  },
  {
    budget_cost_unit: 'руб',
    budget_cost_value: '2654674',
    budget_fact_unit: 'руб',
    budget_fact_value: '1535647',
    budget_plan_unit: 'руб',
    budget_plan_value: '2379165',
    denotation: 'МСТ-2024',
    description: 'Описание проекта 3',
    filesfolder_name: 'modernization_docs',
    goal: 'Цель проекта 3',
    guid: '3586feff-1b42-44a7-8345-6289eac1b22',
    id: '35',
    mainscheduledplan_actualdurationindays: '0',
    mainscheduledplan_actualenddate: null,
    mainscheduledplan_actualstartdate: null,
    mainscheduledplan_durationindays: '308',
    mainscheduledplan_enddate: '31.01.2027',
    mainscheduledplan_name: 'План проекта 3',
    mainscheduledplan_progress: '25 %',
    mainscheduledplan_projectelemanswerableuser_photo: null,
    mainscheduledplan_projectelemanswerableuser_shortname: 'Сидорова А.В.',
    mainscheduledplan_s_guid: '35d7059a-f54a-47e6-ab8b-1b4d8d995a62',
    mainscheduledplan_startdate: '01.08.2025',
    name: 'Проект 3: Создание продукта',
    number: 3,
    parent: '34',
    result: 'В процессе',
    s_classid: 'Подпроект',
    type: 'Подпроект',
  },
  {
    budget_cost_unit: 'руб',
    budget_cost_value: '457217',
    budget_fact_unit: 'руб',
    budget_fact_value: '2803525',
    budget_plan_unit: 'руб',
    budget_plan_value: '1981144',
    denotation: 'ЦПУФ-2024',
    description: 'Описание проекта 4',
    filesfolder_name: 'tech_docs',
    goal: 'Цель проекта 4',
    guid: '3686feff-1b42-44a7-8345-6289eac1b23',
    id: '36',
    mainscheduledplan_actualdurationindays: '0',
    mainscheduledplan_actualenddate: null,
    mainscheduledplan_actualstartdate: '2024-01-20T09:00:00',
    mainscheduledplan_durationindays: '106',
    mainscheduledplan_enddate: '31.01.2027',
    mainscheduledplan_name: 'План проекта 4',
    mainscheduledplan_progress: '25 %',
    mainscheduledplan_projectelemanswerableuser_photo: null,
    mainscheduledplan_projectelemanswerableuser_shortname: 'Кузнецов С.М.',
    mainscheduledplan_s_guid: '36d7059a-f54a-47e6-ab8b-1b4d8d995a63',
    mainscheduledplan_startdate: '01.08.2025',
    name: 'Проект 4: Внедрение процесса',
    number: 4,
    parent: '34',
    result: 'В процессе',
    s_classid: 'Подпроект',
    type: 'Подпроект',
  },
  {
    budget_cost_unit: 'руб',
    budget_cost_value: '2526599',
    budget_fact_unit: 'руб',
    budget_fact_value: '2110955',
    budget_plan_unit: 'руб',
    budget_plan_value: '1364759',
    denotation: 'ОЛМ-2024',
    description: 'Описание проекта 5',
    filesfolder_name: 'research_files',
    goal: 'Цель проекта 5',
    guid: '3786feff-1b42-44a7-8345-6289eac1b24',
    id: '37',
    mainscheduledplan_actualdurationindays: '0',
    mainscheduledplan_actualenddate: null,
    mainscheduledplan_actualstartdate: '2024-01-20T09:00:00',
    mainscheduledplan_durationindays: '219',
    mainscheduledplan_enddate: '31.01.2027',
    mainscheduledplan_name: 'План проекта 5',
    mainscheduledplan_progress: '0 %',
    mainscheduledplan_projectelemanswerableuser_photo: null,
    mainscheduledplan_projectelemanswerableuser_shortname: 'Васильева Е.К.',
    mainscheduledplan_s_guid: '37d7059a-f54a-47e6-ab8b-1b4d8d995a64',
    mainscheduledplan_startdate: '01.08.2025',
    name: 'Проект 5: Оптимизация оборудования',
    number: 5,
    parent: '34',
    result: 'В процессе',
    s_classid: 'Подпроект',
    type: 'Подпроект',
  },
  {
    budget_cost_unit: 'руб',
    budget_cost_value: '3131446',
    budget_fact_unit: 'руб',
    budget_fact_value: '2662194',
    budget_plan_unit: 'руб',
    budget_plan_value: '797181',
    denotation: 'РСТ-2024',
    description: 'Описание проекта 6',
    filesfolder_name: null,
    goal: 'Цель проекта 6',
    guid: '3886feff-1b42-44a7-8345-6289eac1b25',
    id: '38',
    mainscheduledplan_actualdurationindays: '0',
    mainscheduledplan_actualenddate: null,
    mainscheduledplan_actualstartdate: '2024-01-20T09:00:00',
    mainscheduledplan_durationindays: '274',
    mainscheduledplan_enddate: '31.01.2027',
    mainscheduledplan_name: 'План проекта 6',
    mainscheduledplan_progress: '25 %',
    mainscheduledplan_projectelemanswerableuser_photo: null,
    mainscheduledplan_projectelemanswerableuser_shortname: 'Петров П.П.',
    mainscheduledplan_s_guid: '38d7059a-f54a-47e6-ab8b-1b4d8d995a65',
    mainscheduledplan_startdate: '01.08.2025',
    name: 'Проект 6: Разработка системы',
    number: 6,
    parent: '34',
    result: 'В процессе',
    s_classid: 'Подпроект',
    type: 'Подпроект',
  },
  {
    budget_cost_unit: 'руб',
    budget_cost_value: '2694438',
    budget_fact_unit: 'руб',
    budget_fact_value: '667608',
    budget_plan_unit: 'руб',
    budget_plan_value: '2867058',
    denotation: 'РНП-2024',
    description: 'Описание проекта 7',
    filesfolder_name: 'project_files',
    goal: 'Цель проекта 7',
    guid: '3986feff-1b42-44a7-8345-6289eac1b26',
    id: '39',
    mainscheduledplan_actualdurationindays: '0',
    mainscheduledplan_actualenddate: null,
    mainscheduledplan_actualstartdate: '2024-01-20T09:00:00',
    mainscheduledplan_durationindays: '426',
    mainscheduledplan_enddate: '31.01.2027',
    mainscheduledplan_name: 'План проекта 7',
    mainscheduledplan_progress: '50 %',
    mainscheduledplan_projectelemanswerableuser_photo: null,
    mainscheduledplan_projectelemanswerableuser_shortname: 'Иванов И.И.',
    mainscheduledplan_s_guid: '39d7059a-f54a-47e6-ab8b-1b4d8d995a66',
    mainscheduledplan_startdate: '01.08.2025',
    name: 'Проект 7: Модернизация технологии',
    number: 7,
    parent: '34',
    result: 'В процессе',
    s_classid: 'Подпроект',
    type: 'Подпроект',
  },
  {
    budget_cost_unit: 'руб',
    budget_cost_value: '806528',
    budget_fact_unit: 'руб',
    budget_fact_value: '2652601',
    budget_plan_unit: 'руб',
    budget_plan_value: '1365718',
    denotation: 'МСТ-2024',
    description: 'Описание проекта 8',
    filesfolder_name: 'modernization_docs',
    goal: 'Цель проекта 8',
    guid: '4086feff-1b42-44a7-8345-6289eac1b27',
    id: '40',
    mainscheduledplan_actualdurationindays: '0',
    mainscheduledplan_actualenddate: null,
    mainscheduledplan_actualstartdate: '2024-01-20T09:00:00',
    mainscheduledplan_durationindays: '394',
    mainscheduledplan_enddate: '31.01.2027',
    mainscheduledplan_name: 'План проекта 8',
    mainscheduledplan_progress: '90 %',
    mainscheduledplan_projectelemanswerableuser_photo: null,
    mainscheduledplan_projectelemanswerableuser_shortname: 'Сидорова А.В.',
    mainscheduledplan_s_guid: '40d7059a-f54a-47e6-ab8b-1b4d8d995a67',
    mainscheduledplan_startdate: '01.08.2025',
    name: 'Проект 8: Создание продукта',
    number: 8,
    parent: '34',
    result: 'В процессе',
    s_classid: 'Подпроект',
    type: 'Подпроект',
  },
  {
    budget_cost_unit: 'руб',
    budget_cost_value: '1542909',
    budget_fact_unit: 'руб',
    budget_fact_value: '915510',
    budget_plan_unit: 'руб',
    budget_plan_value: '1319865',
    denotation: 'ЦПУФ-2024',
    description: 'Описание проекта 9',
    filesfolder_name: 'tech_docs',
    goal: 'Цель проекта 9',
    guid: '4186feff-1b42-44a7-8345-6289eac1b28',
    id: '41',
    mainscheduledplan_actualdurationindays: '0',
    mainscheduledplan_actualenddate: null,
    mainscheduledplan_actualstartdate: null,
    mainscheduledplan_durationindays: '176',
    mainscheduledplan_enddate: '31.01.2027',
    mainscheduledplan_name: 'План проекта 9',
    mainscheduledplan_progress: '0 %',
    mainscheduledplan_projectelemanswerableuser_photo: null,
    mainscheduledplan_projectelemanswerableuser_shortname: 'Кузнецов С.М.',
    mainscheduledplan_s_guid: '41d7059a-f54a-47e6-ab8b-1b4d8d995a68',
    mainscheduledplan_startdate: '01.08.2025',
    name: 'Проект 9: Внедрение процесса',
    number: 9,
    parent: '34',
    result: 'В процессе',
    s_classid: 'Подпроект',
    type: 'Подпроект',
  },
  {
    budget_cost_unit: 'руб',
    budget_cost_value: '2654674',
    budget_fact_unit: 'руб',
    budget_fact_value: '1535647',
    budget_plan_unit: 'руб',
    budget_plan_value: '2379165',
    denotation: 'МСТ-2024',
    description: 'Описание проекта 3',
    filesfolder_name: 'modernization_docs',
    goal: 'Цель проекта 3',
    guid: '3586feff-1b42-44a7-8345-6289eac1b22',
    id: '35',
    mainscheduledplan_actualdurationindays: '0',
    mainscheduledplan_actualenddate: null,
    mainscheduledplan_actualstartdate: null,
    mainscheduledplan_durationindays: '308',
    mainscheduledplan_enddate: '31.01.2027',
    mainscheduledplan_name: 'План проекта 3',
    mainscheduledplan_progress: '25 %',
    mainscheduledplan_projectelemanswerableuser_photo: null,
    mainscheduledplan_projectelemanswerableuser_shortname: 'Сидорова А.В.',
    mainscheduledplan_s_guid: '35d7059a-f54a-47e6-ab8b-1b4d8d995a62',
    mainscheduledplan_startdate: '01.08.2025',
    name: 'Проект 3: Создание продукта',
    number: 3,
    parent: '34',
    result: 'В процессе',
    s_classid: 'Подпроект',
    type: 'Подпроект',
  },
  {
    budget_cost_unit: 'руб',
    budget_cost_value: '457217',
    budget_fact_unit: 'руб',
    budget_fact_value: '2803525',
    budget_plan_unit: 'руб',
    budget_plan_value: '1981144',
    denotation: 'ЦПУФ-2024',
    description: 'Описание проекта 4',
    filesfolder_name: 'tech_docs',
    goal: 'Цель проекта 4',
    guid: '3686feff-1b42-44a7-8345-6289eac1b23',
    id: '36',
    mainscheduledplan_actualdurationindays: '0',
    mainscheduledplan_actualenddate: null,
    mainscheduledplan_actualstartdate: '2024-01-20T09:00:00',
    mainscheduledplan_durationindays: '106',
    mainscheduledplan_enddate: '31.01.2027',
    mainscheduledplan_name: 'План проекта 4',
    mainscheduledplan_progress: '25 %',
    mainscheduledplan_projectelemanswerableuser_photo: null,
    mainscheduledplan_projectelemanswerableuser_shortname: 'Кузнецов С.М.',
    mainscheduledplan_s_guid: '36d7059a-f54a-47e6-ab8b-1b4d8d995a63',
    mainscheduledplan_startdate: '01.08.2025',
    name: 'Проект 4: Внедрение процесса',
    number: 4,
    parent: '34',
    result: 'В процессе',
    s_classid: 'Подпроект',
    type: 'Подпроект',
  },
  {
    budget_cost_unit: 'руб',
    budget_cost_value: '2526599',
    budget_fact_unit: 'руб',
    budget_fact_value: '2110955',
    budget_plan_unit: 'руб',
    budget_plan_value: '1364759',
    denotation: 'ОЛМ-2024',
    description: 'Описание проекта 5',
    filesfolder_name: 'research_files',
    goal: 'Цель проекта 5',
    guid: '3786feff-1b42-44a7-8345-6289eac1b24',
    id: '37',
    mainscheduledplan_actualdurationindays: '0',
    mainscheduledplan_actualenddate: null,
    mainscheduledplan_actualstartdate: '2024-01-20T09:00:00',
    mainscheduledplan_durationindays: '219',
    mainscheduledplan_enddate: '31.01.2027',
    mainscheduledplan_name: 'План проекта 5',
    mainscheduledplan_progress: '0 %',
    mainscheduledplan_projectelemanswerableuser_photo: null,
    mainscheduledplan_projectelemanswerableuser_shortname: 'Васильева Е.К.',
    mainscheduledplan_s_guid: '37d7059a-f54a-47e6-ab8b-1b4d8d995a64',
    mainscheduledplan_startdate: '01.08.2025',
    name: 'Проект 5: Оптимизация оборудования',
    number: 5,
    parent: '34',
    result: 'В процессе',
    s_classid: 'Подпроект',
    type: 'Подпроект',
  },
  {
    budget_cost_unit: 'руб',
    budget_cost_value: '3131446',
    budget_fact_unit: 'руб',
    budget_fact_value: '2662194',
    budget_plan_unit: 'руб',
    budget_plan_value: '797181',
    denotation: 'РСТ-2024',
    description: 'Описание проекта 6',
    filesfolder_name: null,
    goal: 'Цель проекта 6',
    guid: '3886feff-1b42-44a7-8345-6289eac1b25',
    id: '38',
    mainscheduledplan_actualdurationindays: '0',
    mainscheduledplan_actualenddate: null,
    mainscheduledplan_actualstartdate: '2024-01-20T09:00:00',
    mainscheduledplan_durationindays: '274',
    mainscheduledplan_enddate: '31.01.2027',
    mainscheduledplan_name: 'План проекта 6',
    mainscheduledplan_progress: '25 %',
    mainscheduledplan_projectelemanswerableuser_photo: null,
    mainscheduledplan_projectelemanswerableuser_shortname: 'Петров П.П.',
    mainscheduledplan_s_guid: '38d7059a-f54a-47e6-ab8b-1b4d8d995a65',
    mainscheduledplan_startdate: '01.08.2025',
    name: 'Проект 6: Разработка системы',
    number: 6,
    parent: '39',
    result: 'В процессе',
    s_classid: 'Подпроект',
    type: 'Подпроект',
  },
  {
    budget_cost_unit: 'руб',
    budget_cost_value: '2694438',
    budget_fact_unit: 'руб',
    budget_fact_value: '667608',
    budget_plan_unit: 'руб',
    budget_plan_value: '2867058',
    denotation: 'РНП-2024',
    description: 'Описание проекта 7',
    filesfolder_name: 'project_files',
    goal: 'Цель проекта 7',
    guid: '3986feff-1b42-44a7-8345-6289eac1b26',
    id: '39',
    mainscheduledplan_actualdurationindays: '0',
    mainscheduledplan_actualenddate: null,
    mainscheduledplan_actualstartdate: '2024-01-20T09:00:00',
    mainscheduledplan_durationindays: '426',
    mainscheduledplan_enddate: '31.01.2027',
    mainscheduledplan_name: 'План проекта 7',
    mainscheduledplan_progress: '50 %',
    mainscheduledplan_projectelemanswerableuser_photo: null,
    mainscheduledplan_projectelemanswerableuser_shortname: 'Иванов И.И.',
    mainscheduledplan_s_guid: '39d7059a-f54a-47e6-ab8b-1b4d8d995a66',
    mainscheduledplan_startdate: '01.08.2025',
    name: 'Проект 7: Модернизация технологии',
    number: 7,
    parent: '34',
    result: 'В процессе',
    s_classid: 'Подпроект',
    type: 'Подпроект',
  },
  {
    budget_cost_unit: 'руб',
    budget_cost_value: '806528',
    budget_fact_unit: 'руб',
    budget_fact_value: '2652601',
    budget_plan_unit: 'руб',
    budget_plan_value: '1365718',
    denotation: 'МСТ-2024',
    description: 'Описание проекта 8',
    filesfolder_name: 'modernization_docs',
    goal: 'Цель проекта 8',
    guid: '4086feff-1b42-44a7-8345-6289eac1b27',
    id: '40',
    mainscheduledplan_actualdurationindays: '0',
    mainscheduledplan_actualenddate: null,
    mainscheduledplan_actualstartdate: '2024-01-20T09:00:00',
    mainscheduledplan_durationindays: '394',
    mainscheduledplan_enddate: '31.01.2027',
    mainscheduledplan_name: 'План проекта 8',
    mainscheduledplan_progress: '90 %',
    mainscheduledplan_projectelemanswerableuser_photo: null,
    mainscheduledplan_projectelemanswerableuser_shortname: 'Сидорова А.В.',
    mainscheduledplan_s_guid: '40d7059a-f54a-47e6-ab8b-1b4d8d995a67',
    mainscheduledplan_startdate: '01.08.2025',
    name: 'Проект 8: Создание продукта',
    number: 8,
    parent: '39',
    result: 'В процессе',
    s_classid: 'Подпроект',
    type: 'Подпроект',
  },
  {
    budget_cost_unit: 'руб',
    budget_cost_value: '1542909',
    budget_fact_unit: 'руб',
    budget_fact_value: '915510',
    budget_plan_unit: 'руб',
    budget_plan_value: '1319865',
    denotation: 'ЦПУФ-2024',
    description: 'Описание проекта 9',
    filesfolder_name: 'tech_docs',
    goal: 'Цель проекта 9',
    guid: '4186feff-1b42-44a7-8345-6289eac1b28',
    id: '41',
    mainscheduledplan_actualdurationindays: '0',
    mainscheduledplan_actualenddate: null,
    mainscheduledplan_actualstartdate: null,
    mainscheduledplan_durationindays: '176',
    mainscheduledplan_enddate: '31.01.2027',
    mainscheduledplan_name: 'План проекта 9',
    mainscheduledplan_progress: '0 %',
    mainscheduledplan_projectelemanswerableuser_photo: null,
    mainscheduledplan_projectelemanswerableuser_shortname: 'Кузнецов С.М.',
    mainscheduledplan_s_guid: '41d7059a-f54a-47e6-ab8b-1b4d8d995a68',
    mainscheduledplan_startdate: '01.08.2025',
    name: 'Проект 9: Внедрение процесса',
    number: 9,
    parent: '39',
    result: 'В процессе',
    s_classid: 'Подпроект',
    type: 'Подпроект',
  },
]

export const data_parent_ids = [
  { id: '33', parent: null },
  { id: '34', parent: '33' },
  { id: '35', parent: '34' },
  { id: '36', parent: '34' },
  { id: '37', parent: '34' },
  { id: '38', parent: '34' },
  { id: '39', parent: '34' },
  { id: '40', parent: '34' },
  { id: '41', parent: '34' },
  { id: '35', parent: '34' },
  { id: '36', parent: '34' },
  { id: '37', parent: '34' },
  { id: '38', parent: '39' },
  { id: '39', parent: '34' },
  { id: '40', parent: '39' },
  { id: '41', parent: '39' },
]
